apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myconfig.properties: |
    myConfig1:
      nonUpdatableParameter1: {{ include "demo-merging-dynamic-configuration-in-helm.baseConfig.myConfig1.nonUpdatableParameter1" . }}
      parameter11: {{ .Values.config.myConfig1.parameter11 }}
      parameter12: {{ .Values.config.myConfig1.parameter12 }}
    myConfig2:
      parameter21: {{ .Values.config.myConfig2.parameter21 }}
    nonUpdatableOption1: {{ include "demo-merging-dynamic-configuration-in-helm.baseConfig.nonUpdatableOption1" . }}
    option2: {{ .Values.config.option2 }}

